version: "3.8"

services:
  app:
    container_name: resticted
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
    restart: unless-stopped
    command: python3 main.py
